name: ctt test

on:
  issues:
    types: [opened, edited, reopened]
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check fill
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-start: '|'
          require-include: 'English'
          comment-body: 'Check failed.'
          skip-title-start: 'docs'
